# -*- coding: utf-8 -*-
"""KKBOX_datacrawler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142W7Ltp1TboOzFr_o0vUrUYVl9iOOhvR
"""

import requests
import json

from bs4 import BeautifulSoup

url = 'https://kma.kkbox.com/charts/api/v1/yearly?category=297&lang=tc&limit=50&terr=tw&year=2022'
response = requests.get(url)
data = json.loads(response.text)
song_list = data["data"]["charts"]["newrelease"]
# 取得每首歌的排名、曲名、連結、作者、時間
for song in song_list:
    song_rank = song["rankings"]["this_period"]
    song_name = song["song_name"]
    song_url = song["song_url"]
    song_artist = song["artist_name"]
    song_timestamp = int(song["release_date"])
    song_response = requests.get(song_url)
    soup = BeautifulSoup(song_response.text, "html.parser")
    lyric = soup.find("div", class_="lyrics").text
    
  
    print("排名:", song_rank)
    print("歌名:", song_name)
    print("作者:", song_artist)
    print("歌詞:", lyric)